Reading dataframe
```{r}
data <- read.csv("weather.csv", sep = ";", na.strings = "", stringsAsFactors = TRUE)
summary(data)
View(head(data))
View(tail(data))
```

Renaming columns
```{r}
colnames(data) <- c("Weather", "Temperature", "Humidity", "Wind", "PlayGame")
colnames(data)
```
Exploring Weather Rows - Wrong Weather Factor (1)
```{r}
summary(data$Weather)
data$Weather <- as.character(data$Weather)
data$Weather[data$Weather == "sol"] <- "Sunny"
data$Weather[data$Weather == "nublado"] <- "Cloudy"
data$Weather[data$Weather == "chuva"] <- "Rainy"
data$Weather <- factor(data$Weather)
```
Exploring Temperature Data - 130 ~ 130 F | Outlier (1)
```{r}
View(head(data))
counts <- table(data$Temperature)
counts
summary(data$Temperature)
boxplot(data$Temperature, outline = FALSE)
hist(data$Temperature)
```
Exploring Humidity Data - 0 ~ 100 | NA's (1), Outlier (1)
```{r}
summary(data$Humidity)
boxplot(data$Humidity)
hist(data$Humidity)
```
Exploring Wind Data - NA's (1)
```{r}
summary(data$Wind)
```
Exploring PlayGame Data
```{r}
summary(data$PlayGame)
data$PlayGame <- as.character(data$PlayGame)
data$PlayGame[data$PlayGame == "sim"] <- "Yes"
data$PlayGame[data$PlayGame == "nao"] <- "No"
data$PlayGame <- factor(data$PlayGame)
data$PlayGame
```
Data Cleaning - Weather | Wrong Weather Factor (1)
```{r}
unique(data$Weather)
summary(data$Weather)
data$Weather[!data$Weather %in% c("Sunny", "Cloudy", "Rainy")] <- "Sunny"
data$Weather <- factor(data$Weather)
summary(data$Weather)
```
Data Cleaning - Temperature | Outlier | Max Value: 130 (1)
```{r}
summary(data$Temperature)
data$Temperature[data$Temperature > 130] <- median(data$Temperature, na.rm = TRUE)
```
Data Cleaning - Humidity | Outlier (1) | Max Value: 100
```{r}
summary(data$Humidity)
data$Humidity[data$Humidity > 100] <- median(data$Humidity, na.rm = TRUE)
data <- data[!is.na(data$Humidity), ]
```
